"""Backward-compatibility proxy for pageindex_parser.py.

Implementation moved to the pageindex package.
"""

from drbrain.parser.pageindex import (  # noqa: F401
    DocumentTree,
    TreeConfig,
    _build_tree_from_nodes,
    _build_tree_from_outline,
    _cap_depth,
    _clean_tree_for_output,
    _collect_line_ranges,
    _count_leaves,
    _create_clean_structure_for_description,
    _extract_node_text_content,
    _extract_nodes_from_markdown,
    _extract_pdf_outline,
    _find_all_children,
    _find_node_by_id,
    _flatten_single_chains,
    _format_structure,
    _generate_doc_description,
    _generate_node_summary,
    _generate_summaries_for_structure_md,
    _llm_segment_document,
    _recursive_split_large_nodes,
    _split_large_text,
    _split_single_leaf,
    _structure_to_list,
    _tree_thinning_for_index,
    _update_node_list_with_text_token_count,
    _verify_and_correct_tree,
    _verify_tree_sample,
    _write_node_id,
    get_document_structure_json,
    get_node_content,
    get_node_content_by_title,
    md_to_tree,
    md_to_tree_with_fallback,
    validate_and_fix_tree,
)
